### PR TITLE
Edge display issues

### LINKED ISSUE #22: Display issues on Edge
### What's up?

[Reported](https://twitter.com/scshepard/status/831777343282749442) by @scshepard

image

### Mkay, tell me more...

I managed to do a quick IE debugging session on BrowserStack (Edge was not available on trial, but the error was reproduced) and found that adding `position: relative` to some divs fixed the problem.

On top of this, the entire build was broken in IE due to the fact that the version I tested in had no support for Promises. I'll include [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) in the build to fix this.

### PR DESCRIPTION
**Pull request by skidding**
Fix #22 

> Apparently wrapper needs position rel/abs in order for its opacity to
apply to child elements with position absolute

### CODE REVIEW

**Comment by skidding** [comment]
@scshepard is it possible for you to test this branch on your machine (clone + `npm i` + `npm run dev`, provided you have Node installed)? Thanks.

**Comment by skidding** [comment]
@scshepard already deployed this because I think it fixes the problem and I wanted to put it out there ASAP for Windows users. Let me know if you manage to test on your device anyway. No need to install locally anymore as the update is live at https://illustrated-algorithms.now.sh/quicksort

**Comment by demoneaux** [comment]
Tested with both Edge and IE 11, seems to be working great!

**Comment by skidding** [comment]
@demoneaux thanks!

**Pull request merged**
